module.exports = {
  "ALIVE_IMG": "https://telegra.ph/file/ef48cc8d2d26081f7d46a.jpg",
  "FOOT": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "PREFIX": ".",
  "SESSION_ID": "Manu-MD&WBE3yRCR#iFmzZQhAD7o03icBN7tz_d_qcIWcbiMd058qfKHQjNQ",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "26777821911",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "fasle",
  "ANTI_BOT": "false",
  "ANTI_CALL": "fasle",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "false",
  "ANTI_STICKER": "false",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "Njabulo JB Office",
  "OWNER_NUMBER": "26777821911",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
};
